package com.tsy.plutusnative.model;

enum Status {
    AVAILABLE_TO_REQUEST,
    AVAILABLE_TO_UPLOAD_VIDEO,
    DEEPLY_PHONE_VERIFICATION_REQUIRED,
    WAITING_FOR_RELEASE,
    LOAN_SUCCEED,
    UPLOADED_REPAY_BILL,
    PENDING_WORKING,
    UNKNOWN
}
